daedongbread/bread-map-backend-2

src/main/java/com/depromeet/breadmapbackend/domain/bakery/repository/ReviewRepositorySupport.java
src/main/java/com/depromeet/breadmapbackend/service/review/ReviewService.java
src/main/java/com/depromeet/breadmapbackend/service/review/ReviewServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/web/controller/review/ReviewController.java
src/main/java/com/depromeet/breadmapbackend/web/controller/review/dto/SimpleReviewDto.java
src/main/resources/application.yml

[Review API] 모든 리뷰를 반환하는 api 제작

---

src/docs/asciidoc/index.adoc
src/main/java/com/depromeet/breadmapbackend/domain/review/repository/ReviewRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/user/Follow.java
src/main/java/com/depromeet/breadmapbackend/domain/user/exception/FollowAlreadyException.java
src/main/java/com/depromeet/breadmapbackend/domain/user/exception/FollowNotFoundException.java
src/main/java/com/depromeet/breadmapbackend/domain/user/repository/FollowRepository.java
src/main/java/com/depromeet/breadmapbackend/infra/SecurityConfig.java
src/main/java/com/depromeet/breadmapbackend/service/review/ReviewService.java
src/main/java/com/depromeet/breadmapbackend/service/review/ReviewServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/service/user/UserService.java
src/main/java/com/depromeet/breadmapbackend/service/user/UserServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/web/controller/review/ReviewController.java
src/main/java/com/depromeet/breadmapbackend/web/controller/review/dto/ReviewDetailDto.java
src/main/java/com/depromeet/breadmapbackend/web/controller/review/dto/ReviewDto.java
src/main/java/com/depromeet/breadmapbackend/web/controller/user/UserController.java
src/main/java/com/depromeet/breadmapbackend/web/controller/user/dto/FollowDto.java
src/main/java/com/depromeet/breadmapbackend/web/controller/user/dto/FollowRequest.java
src/main/java/com/depromeet/breadmapbackend/web/controller/user/dto/ProfileDto.java
src/main/java/com/depromeet/breadmapbackend/web/controller/user/dto/UserFlagDto.java
src/main/java/com/depromeet/breadmapbackend/web/controller/user/dto/UserReviewDto.java
src/main/resources/static/docs/index.html
src/test/java/com/depromeet/breadmapbackend/restdocs/utils/ControllerTest.java
src/test/java/com/depromeet/breadmapbackend/web/controller/flag/FlagControllerTest.java
src/test/java/com/depromeet/breadmapbackend/web/controller/review/ReviewControllerTest.java
src/test/java/com/depromeet/breadmapbackend/web/controller/user/UserControllerTest.java

- 프로필 조회 API
- 팔로우 API
- 언팔로우 API
- 팔로워 리스트 조회 API
- 팔로잉 리스트 조회 API

feat : 프로필 조회 API 및 팔로잉 관련 API 작성

---

.gitignore
build.gradle
src/main/java/com/depromeet/breadmapbackend/domain/notice/Notice.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/NoticeToken.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/NoticeType.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/exception/NoticeDateException.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/exception/NoticeTypeWrongException.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/repository/NoticeRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/repository/NoticeTokenRepository.java
src/main/java/com/depromeet/breadmapbackend/infra/EmbeddedRedisConfig.java
src/main/java/com/depromeet/breadmapbackend/infra/FirebaseConfig.java
src/main/java/com/depromeet/breadmapbackend/infra/RedisConfig.java
src/main/java/com/depromeet/breadmapbackend/infra/SecurityConfig.java
src/main/java/com/depromeet/breadmapbackend/service/notice/FcmService.java
src/main/java/com/depromeet/breadmapbackend/service/notice/NoticeService.java
src/main/java/com/depromeet/breadmapbackend/service/notice/NoticeServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/web/controller/notice/NoticeController.java
src/main/java/com/depromeet/breadmapbackend/web/controller/notice/dto/FcmMessage.java
src/main/java/com/depromeet/breadmapbackend/web/controller/notice/dto/NoticeDto.java
src/main/resources/application-prod.yml
src/main/resources/application.yml
src/main/resources/firebase/firebase-service-key.json
src/test/java/com/depromeet/breadmapbackend/utils/ControllerTest.java

feat : FCM push 알림 구현, Redis 설정

---

src/docs/asciidoc/index.adoc
src/main/java/com/depromeet/breadmapbackend/domain/user/BlockUser.java
src/main/java/com/depromeet/breadmapbackend/domain/user/exception/BlockAlreadyException.java
src/main/java/com/depromeet/breadmapbackend/domain/user/exception/BlockNotFoundException.java
src/main/java/com/depromeet/breadmapbackend/domain/user/repository/BlockUserRepository.java
src/main/java/com/depromeet/breadmapbackend/service/user/UserService.java
src/main/java/com/depromeet/breadmapbackend/service/user/UserServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/web/advice/ExceptionAdvice.java
src/main/java/com/depromeet/breadmapbackend/web/controller/user/UserController.java
src/main/java/com/depromeet/breadmapbackend/web/controller/user/dto/BlockRequest.java
src/main/java/com/depromeet/breadmapbackend/web/controller/user/dto/SimpleUserDto.java
src/main/resources/static/docs/index.html
src/test/java/com/depromeet/breadmapbackend/utils/ControllerTest.java
src/test/java/com/depromeet/breadmapbackend/web/controller/user/UserControllerTest.java

- 유저 차단 API
- 유저 차단 해제 API
- 차단 리스트 API

feat : 유저 차단/차단 해제 API 및 차단 리스트 API 구현, 에러 코드 추가

---

src/docs/asciidoc/index.adoc
src/main/java/com/depromeet/breadmapbackend/domain/bakery/repository/BakeryRepository.java
src/main/java/com/depromeet/breadmapbackend/infra/SecurityConfig.java
src/main/java/com/depromeet/breadmapbackend/service/search/SearchService.java
src/main/java/com/depromeet/breadmapbackend/service/search/SearchServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/web/controller/search/SearchController.java
src/main/java/com/depromeet/breadmapbackend/web/controller/search/dto/SearchDto.java
src/main/resources/static/docs/index.html
src/test/java/com/depromeet/breadmapbackend/web/controller/bakery/BakeryControllerTest.java
src/test/java/com/depromeet/breadmapbackend/web/controller/flag/FlagControllerTest.java
src/test/java/com/depromeet/breadmapbackend/web/controller/review/ReviewControllerTest.java
src/test/java/com/depromeet/breadmapbackend/web/controller/search/SearchControllerTest.java
src/test/java/com/depromeet/breadmapbackend/web/controller/user/UserControllerTest.java

- 자동 완성 API
- 검색 API
- 최근 검색어 조회 API
- 최근 검색어 단건 삭제 API
- 최근 검색어 전체 삭제 API
자동 완성은 추후에 레디스로 구현 예정

feat : 자동 완성 API, 검색 API, 최근 검색어 조회 API, 최근 검색어 단건/전체 삭제 API 구현

---

src/main/java/com/depromeet/breadmapbackend/service/search/SearchService.java
src/main/java/com/depromeet/breadmapbackend/service/search/SearchServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/web/controller/search/SearchController.java
src/main/resources/static/docs/index.html
src/test/java/com/depromeet/breadmapbackend/web/controller/search/SearchControllerTest.java

fix : 검색 API 수정

---

src/main/java/com/depromeet/breadmapbackend/web/advice/ExceptionAdvice.java
src/main/resources/application-prod.yml
src/main/resources/application.yml

hotfix : 로그 설정 변경, 레디스 설정 추가

---

src/docs/asciidoc/index.adoc
src/main/java/com/depromeet/breadmapbackend/domain/bakery/repository/BreadRepository.java
src/main/java/com/depromeet/breadmapbackend/service/bakery/BakeryService.java
src/main/java/com/depromeet/breadmapbackend/service/bakery/BakeryServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/service/review/ReviewService.java
src/main/java/com/depromeet/breadmapbackend/service/review/ReviewServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/web/controller/bakery/BakeryController.java
src/main/java/com/depromeet/breadmapbackend/web/controller/bakery/dto/SimpleBreadDto.java
src/main/resources/static/docs/index.html
src/test/java/com/depromeet/breadmapbackend/web/controller/bakery/BakeryControllerTest.java

- 리뷰용 빵 간단 리스트 조회 API
- 리뷰용 빵 검색 API

feat : 리뷰용 빵 간단 리스트 조회 API, 리뷰용 빵 검색 API 구현

---

src/docs/asciidoc/index.adoc
src/main/java/com/depromeet/breadmapbackend/domain/flag/repository/FlagBakeryRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/flag/repository/FlagRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/repository/NoticeRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/repository/NoticeTokenRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/review/repository/ReviewCommentLikeRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/review/repository/ReviewCommentRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/review/repository/ReviewLikeRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/review/repository/ReviewRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/user/repository/BlockUserRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/user/repository/FollowRepository.java
src/main/java/com/depromeet/breadmapbackend/service/review/ReviewServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/service/user/UserService.java
src/main/java/com/depromeet/breadmapbackend/service/user/UserServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/web/controller/user/UserController.java
src/main/resources/static/docs/index.html
src/test/java/com/depromeet/breadmapbackend/web/controller/user/UserControllerTest.java

feat : 유저 탈퇴 API 구현

---

src/docs/asciidoc/index.adoc
src/main/java/com/depromeet/breadmapbackend/infra/SecurityConfig.java
src/main/java/com/depromeet/breadmapbackend/security/exception/RejoinException.java
src/main/java/com/depromeet/breadmapbackend/security/handler/OAuth2AuthenticationSuccessHandler.java
src/main/java/com/depromeet/breadmapbackend/security/service/CustomOAuth2UserService.java
src/main/java/com/depromeet/breadmapbackend/security/token/JwtTokenProvider.java
src/main/java/com/depromeet/breadmapbackend/service/search/SearchServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/service/user/UserService.java
src/main/java/com/depromeet/breadmapbackend/service/user/UserServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/web/advice/ExceptionAdvice.java
src/main/java/com/depromeet/breadmapbackend/web/controller/user/UserController.java
src/main/java/com/depromeet/breadmapbackend/web/controller/user/dto/TokenRequest.java
src/main/resources/application-prod.yml
src/main/resources/application.yml
src/main/resources/static/docs/index.html
src/test/java/com/depromeet/breadmapbackend/utils/ControllerTest.java
src/test/java/com/depromeet/breadmapbackend/web/controller/user/UserControllerTest.java

- 로그아웃 API 구현
- 회원 탈퇴, 토큰 재발급, 로그인, 로그아웃 로직 Redis로 전환

feat : 로그아웃 API 구현 및 회원 탈퇴, 토큰 재발급, 로그인, 로그아웃 로직 Redis로 전환

---

src/main/java/com/depromeet/breadmapbackend/domain/bakery/Bread.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/exception/BreadAlreadyException.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/repository/BreadRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/review/BreadRating.java
src/main/java/com/depromeet/breadmapbackend/domain/review/Review.java
src/main/java/com/depromeet/breadmapbackend/service/bakery/BakeryServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/service/review/ReviewServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/web/advice/ExceptionAdvice.java
src/main/java/com/depromeet/breadmapbackend/web/controller/review/dto/ReviewRequest.java
src/main/resources/static/docs/index.html
src/test/java/com/depromeet/breadmapbackend/web/controller/flag/FlagControllerTest.java
src/test/java/com/depromeet/breadmapbackend/web/controller/review/ReviewControllerTest.java
src/test/java/com/depromeet/breadmapbackend/web/controller/user/UserControllerTest.java

- 리뷰 추가 API에 빵집에 없는 빵 추가 설정
- 리뷰 isUse  설정 변경

feat : 리뷰 추가 API에 빵집에 없는 빵 추가 설정 및 리뷰 isUse  설정 변경

---

src/docs/asciidoc/index.adoc
src/main/java/com/depromeet/breadmapbackend/domain/bakery/repository/BreadRepository.java
src/main/java/com/depromeet/breadmapbackend/service/bakery/BakeryService.java
src/main/java/com/depromeet/breadmapbackend/service/bakery/BakeryServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/service/review/ReviewService.java
src/main/java/com/depromeet/breadmapbackend/service/review/ReviewServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/web/controller/bakery/BakeryController.java
src/main/java/com/depromeet/breadmapbackend/web/controller/bakery/dto/BakeryDto.java
src/main/java/com/depromeet/breadmapbackend/web/controller/review/ReviewController.java
src/main/resources/static/docs/index.html
src/test/java/com/depromeet/breadmapbackend/web/controller/bakery/BakeryControllerTest.java
src/test/java/com/depromeet/breadmapbackend/web/controller/review/ReviewControllerTest.java

- 빵 리스트 조회 API
- 빵집 조회 API에 리뷰 추가

feat : 빵 리스트 조회 API 구현 및 빵집 조회 API에 리뷰 추가

---

src/docs/asciidoc/index.adoc
src/main/java/com/depromeet/breadmapbackend/domain/user/exception/NickNameAlreadyException.java
src/main/java/com/depromeet/breadmapbackend/domain/user/repository/UserRepository.java
src/main/java/com/depromeet/breadmapbackend/security/service/CustomOAuth2UserService.java
src/main/java/com/depromeet/breadmapbackend/service/user/UserService.java
src/main/java/com/depromeet/breadmapbackend/service/user/UserServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/web/advice/ExceptionAdvice.java
src/main/java/com/depromeet/breadmapbackend/web/controller/user/UserController.java
src/main/java/com/depromeet/breadmapbackend/web/controller/user/dto/UpdateNickNameRequest.java
src/main/resources/static/docs/index.html
src/test/java/com/depromeet/breadmapbackend/web/controller/user/UserControllerTest.java

feat : 닉네임 정책 추가, 닉네임 수정 API

---

src/docs/asciidoc/user.adoc
src/main/java/com/depromeet/breadmapbackend/domain/review/repository/ReviewImageRepository.java
src/main/java/com/depromeet/breadmapbackend/service/notice/NoticeServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/service/user/UserService.java
src/main/java/com/depromeet/breadmapbackend/service/user/UserServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/web/controller/notice/dto/NoticeDto.java
src/main/java/com/depromeet/breadmapbackend/web/controller/user/UserController.java
src/main/java/com/depromeet/breadmapbackend/web/controller/user/dto/ProfileDto.java
src/main/resources/application.yml
src/main/resources/static/docs/admin.html
src/main/resources/static/docs/bakery.html
src/main/resources/static/docs/flag.html
src/main/resources/static/docs/notice.html
src/main/resources/static/docs/review.html
src/main/resources/static/docs/search.html
src/main/resources/static/docs/user.html
src/test/java/com/depromeet/breadmapbackend/web/controller/notice/NoticeControllerTest.java
src/test/java/com/depromeet/breadmapbackend/web/controller/user/UserControllerTest.java

본인 프로필 조회, 타인 프로필 조회 API
API 문서 최신화
유저 탈퇴시 7일간 가입 금지 임시 주석 처리

대동빵지도 0.1.1

---

src/main/java/com/depromeet/breadmapbackend/domain/auth/AuthServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/global/security/token/OIDCProvider.java

- 로그인 문제 해결
- admin 토큰 테스트 에러 수정

refactor : 로그인 문제 해결, admin 토큰 테스트 에러 수정

---

.github/workflows/prod_CD.yml
.github/workflows/prod_CI.yml
.github/workflows/stage_CD.yml
.github/workflows/stage_CI.yml
src/docs/asciidoc/index.adoc
src/main/java/com/depromeet/breadmapbackend/global/exception/ExceptionAdvice.java
src/main/java/com/depromeet/breadmapbackend/global/infra/SecurityConfig.java
src/main/java/com/depromeet/breadmapbackend/global/infra/filter/LoggingFilter.java

- CICD 수정
- SecurityConfig denyAll 제거
- 기본 Exception 추가
- MultpartFile 체크 로직 추가

refactor : CICD 수정, SecurityConfig denyAll 제거, 기본 Exception 추가, MultpartFile 체크 로직 추가

---

.github/workflows/prod_CD.yml
src/main/java/com/depromeet/breadmapbackend/domain/admin/AdminServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/auth/AuthServiceImpl.java
src/test/java/com/depromeet/breadmapbackend/domain/admin/bakery/AdminBakeryControllerTest.java

- admin reissue 에러 해결
- prod CD 수정

refactor : admin reissue 에러 해결, prod CD 수정

---

src/docs/asciidoc/admin.adoc
src/main/java/com/depromeet/breadmapbackend/domain/admin/bakery/AdminBakeryController.java
src/main/java/com/depromeet/breadmapbackend/domain/admin/bakery/AdminBakeryService.java
src/main/java/com/depromeet/breadmapbackend/domain/admin/bakery/AdminBakeryServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/admin/bakery/dto/AdminImageRegisterRequest.java
src/main/java/com/depromeet/breadmapbackend/domain/admin/bakery/dto/NewReviewDto.java
src/main/java/com/depromeet/breadmapbackend/domain/review/Review.java
src/main/java/com/depromeet/breadmapbackend/domain/review/ReviewImage.java
src/main/java/com/depromeet/breadmapbackend/domain/review/ReviewImageRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/review/ReviewQueryRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/review/ReviewRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/review/ReviewServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/review/comment/ReviewCommentServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/review/like/ReviewLikeServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/review/report/ReviewReportServiceImpl.java
src/main/resources/static/docs/admin.html
src/main/resources/static/docs/auth.html
src/main/resources/static/docs/bakery.html
src/main/resources/static/docs/flag.html
src/main/resources/static/docs/image.html
src/main/resources/static/docs/index.html
src/main/resources/static/docs/notice.html
src/main/resources/static/docs/review.html
src/main/resources/static/docs/search.html
src/main/resources/static/docs/user.html
src/test/java/com/depromeet/breadmapbackend/domain/admin/bakery/AdminBakeryControllerTest.java

- 관리자 신규 리뷰 조회/신규 리뷰 숨김/신규 리뷰 이미지 등록/리뷰 삭제 API
- Review/ReviewImage 필드 추가
- review 조회시 필터링 수정

대동빵 stage 0.0.7

---

src/main/java/com/depromeet/breadmapbackend/domain/admin/bakery/AdminBakeryServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/admin/bakery/dto/AdminBakeryIsNewDto.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryQueryRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/product/report/ProductAddReportImage.java
src/main/java/com/depromeet/breadmapbackend/domain/review/ReviewImage.java
src/main/java/com/depromeet/breadmapbackend/domain/review/ReviewRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/review/dto/ReviewDto.java
src/main/resources/static/docs/admin.html
src/main/resources/static/docs/auth.html
src/main/resources/static/docs/bakery.html
src/main/resources/static/docs/flag.html
src/main/resources/static/docs/image.html
src/main/resources/static/docs/notice.html
src/main/resources/static/docs/review.html
src/main/resources/static/docs/search.html
src/main/resources/static/docs/user.html
src/test/java/com/depromeet/breadmapbackend/domain/admin/bakery/AdminBakeryControllerTest.java

- 관리자 빵집 조건 조회 에러 수정
- ProductAddReportImage/ReviewImage isNew 기본값 수정 및 register 로직 수정
- 관리자 빵집 신규 리뷰 여부 필드 추가

대동빵 stage 0.0.8

---

src/main/java/com/depromeet/breadmapbackend/domain/review/ReviewServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/review/dto/ReviewRequest.java
src/main/resources/static/docs/admin.html
src/main/resources/static/docs/auth.html
src/main/resources/static/docs/bakery.html
src/main/resources/static/docs/flag.html
src/main/resources/static/docs/image.html
src/main/resources/static/docs/notice.html
src/main/resources/static/docs/review.html
src/main/resources/static/docs/search.html
src/main/resources/static/docs/user.html
src/test/java/com/depromeet/breadmapbackend/domain/review/ReviewControllerTest.java

대동빵 stage 0.0.9

---

src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryServiceImpl.java
src/test/java/com/depromeet/breadmapbackend/domain/admin/bakery/AdminBakeryControllerTest.java

- 빵집 조회수 로직 에러 수정
- 관리자 빵집 추가/수정 API 문서 수정

대동빵 stage 0.1.0

---

src/main/java/com/depromeet/breadmapbackend/domain/review/ReviewServiceImpl.java

대동빵 1.0.4.1

---

src/main/java/com/depromeet/breadmapbackend/domain/bakery/Bakery.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/product/BakeryProductServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/report/BakeryReportServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/flag/FlagIcon.java
src/main/java/com/depromeet/breadmapbackend/domain/flag/FlagServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/flag/dto/FlagInfo.java
src/main/java/com/depromeet/breadmapbackend/domain/review/Review.java
src/main/java/com/depromeet/breadmapbackend/domain/review/ReviewQueryRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/review/ReviewRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/review/ReviewServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/global/exception/DaedongStatus.java
src/main/resources/static/docs/admin.html
src/main/resources/static/docs/auth.html
src/main/resources/static/docs/bakery.html
src/main/resources/static/docs/flag.html
src/main/resources/static/docs/image.html
src/main/resources/static/docs/notice.html
src/main/resources/static/docs/review.html
src/main/resources/static/docs/search.html
src/main/resources/static/docs/user.html
src/test/java/com/depromeet/breadmapbackend/domain/flag/FlagControllerTest.java

- flag repsonse에 icon 필드 추가
- 빵집 status filtering 추가
- review filtering 일부 추가

대동빵 stage 0.1.1

---

src/main/java/com/depromeet/breadmapbackend/domain/auth/AuthServiceImpl.java

대동빵 1.0.6.1

---

src/main/java/com/depromeet/breadmapbackend/domain/admin/bakery/AdminBakeryServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/admin/bakery/dto/BakeryAddRequest.java
src/main/java/com/depromeet/breadmapbackend/domain/admin/bakery/dto/BakeryUpdateRequest.java
src/main/java/com/depromeet/breadmapbackend/domain/auth/AuthServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/Bakery.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/dto/BakeryDto.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/report/BakeryAddEvent.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/Notice.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/NoticeService.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/NoticeServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/dto/NoticeDto.java
src/main/resources/static/docs/admin.html
src/main/resources/static/docs/auth.html
src/main/resources/static/docs/bakery.html
src/main/resources/static/docs/flag.html
src/main/resources/static/docs/image.html
src/main/resources/static/docs/notice.html
src/main/resources/static/docs/review.html
src/main/resources/static/docs/search.html
src/main/resources/static/docs/user.html
src/test/java/com/depromeet/breadmapbackend/domain/admin/bakery/AdminBakeryControllerTest.java
src/test/java/com/depromeet/breadmapbackend/domain/bakery/BakeryControllerTest.java
src/test/java/com/depromeet/breadmapbackend/domain/notice/NoticeControllerTest.java

빵집 개척 기능
토큰 재발급시 카카오 이메일이 없으면 로그인으로 유도

대동빵 stage 0.1.2

---

src/main/java/com/depromeet/breadmapbackend/domain/bakery/report/BakeryAddReport.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/report/BakeryAddReportImage.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/report/BakeryAddReportImageRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/report/BakeryReportServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/report/dto/BakeryAddReportRequest.java
src/main/resources/static/docs/admin.html
src/main/resources/static/docs/auth.html
src/main/resources/static/docs/bakery.html
src/main/resources/static/docs/flag.html
src/main/resources/static/docs/image.html
src/main/resources/static/docs/notice.html
src/main/resources/static/docs/review.html
src/main/resources/static/docs/search.html
src/main/resources/static/docs/user.html
src/test/java/com/depromeet/breadmapbackend/domain/bakery/report/BakeryReportControllerTest.java
src/test/java/com/depromeet/breadmapbackend/utils/ControllerTest.java

대동빵 stage 0.1.3

---

src/main/java/com/depromeet/breadmapbackend/domain/admin/bakery/AdminBakeryServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/Bakery.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryController.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryServiceImpl.java

- 빵집 리스트 조회 API 로직 간소화
- 관리자 빵집 업데이트 API 개척자 관련 로직 수정

대동빵 stage 0.1.4

---

src/main/java/com/depromeet/breadmapbackend/domain/notice/NoticeServiceImpl.java

대동빵 stage 0.1.6

---

src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/search/SearchServiceImpl.java

대동빵 stage 0.1.7

---

src/main/java/com/depromeet/breadmapbackend/domain/admin/bakery/AdminBakeryServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/admin/bakery/dto/AdminBakeryDto.java
src/main/java/com/depromeet/breadmapbackend/domain/admin/bakery/dto/BakeryAddRequest.java
src/main/java/com/depromeet/breadmapbackend/domain/admin/bakery/dto/BakeryUpdateRequest.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/Bakery.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/dto/BakeryDto.java
src/main/java/com/depromeet/breadmapbackend/domain/search/SearchServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/search/dto/SearchDto.java
src/main/resources/static/docs/admin.html
src/main/resources/static/docs/auth.html
src/main/resources/static/docs/bakery.html
src/main/resources/static/docs/flag.html
src/main/resources/static/docs/image.html
src/main/resources/static/docs/notice.html
src/main/resources/static/docs/review.html
src/main/resources/static/docs/search.html
src/main/resources/static/docs/user.html
src/test/java/com/depromeet/breadmapbackend/domain/admin/bakery/AdminBakeryControllerTest.java
src/test/java/com/depromeet/breadmapbackend/domain/search/SearchControllerTest.java

빵집 검색 시 주소 및 점수 필드 추가
빵집 상세 주소 추가

대동빵 stage 0.1.8

---

src/main/java/com/depromeet/breadmapbackend/domain/admin/bakery/AdminBakeryServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/global/infra/properties/CustomSGISKeyProperties.java
src/main/resources/application-prod.yml
src/main/resources/application-stage.yml
src/main/resources/application.yml
src/test/resources/application.yml

- SGIS properties에 src, dst 추가
- SGIS transcoord exception 추가
- application.yml에서 OAuth 관련 제거

refactor : SGIS properties 수정, SGIS transcoord exception 추가, application.yml에서 OAuth 관련 제거

---

src/main/java/com/depromeet/breadmapbackend/global/infra/filter/LoggerTrxKey.java
src/main/java/com/depromeet/breadmapbackend/global/infra/filter/LoggingFilter.java
src/main/resources/logback-spring-mdc.xml
src/main/resources/logback-spring.xml
src/main/resources/logback-variables.properties

Logger 수정 
logback mdc 
request time 
추가

refactor : request thread id 할당 total request time log 추가

---

README.md

docs : README Infra 구조도 추가

---

src/main/java/com/depromeet/breadmapbackend/domain/flag/FlagServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/review/ReviewQueryRepository.java
src/test/java/com/depromeet/breadmapbackend/domain/flag/FlagServiceImplTest.java
src/test/java/com/depromeet/breadmapbackend/domain/flag/FlagServiceTest.java
src/test/java/com/depromeet/breadmapbackend/domain/notice/NoticeServiceTest.java
src/test/java/com/depromeet/breadmapbackend/utils/ServiceTest.java
src/test/resources/flag-test-data.sql

Refactor : FlagService::removeBakeryToFlag

---

.github/workflows/prod_CD.yml
.github/workflows/prod_CI.yml
.github/workflows/stage_CD.yml
.github/workflows/stage_CI.yml
.gitignore
build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/resources/static/docs/admin.html
src/main/resources/static/docs/auth.html
src/main/resources/static/docs/bakery.html
src/main/resources/static/docs/flag.html
src/main/resources/static/docs/image.html
src/main/resources/static/docs/notice.html
src/main/resources/static/docs/review.html
src/main/resources/static/docs/search.html
src/main/resources/static/docs/user.html

- 기존 access key와 secret key로 접근하는 방식에서 OIDC로 접근하도록 변경
- actions/checkout V2 -> V3

infra : GitHub Actions AWS 접근 OIDC 방식으로 변경

---

src/main/java/com/depromeet/breadmapbackend/domain/review/comment/ReviewCommentServiceImpl.java
src/test/java/com/depromeet/breadmapbackend/domain/review/comment/ReviewCommentControllerTest.java
src/test/java/com/depromeet/breadmapbackend/domain/review/comment/ReviewCommentServiceImplTest.java
src/test/java/com/depromeet/breadmapbackend/domain/review/comment/ReviewCommentServiceTest.java
src/test/resources/review-comment-test-data.sql

테스트 코드 추가 
메소드 리팩토링
발생 이벤트 검증 로직 추가

Refactor : ReviewCommentServiceImpl::addReviewComment 

---

src/main/java/com/depromeet/breadmapbackend/domain/flag/Flag.java
src/main/java/com/depromeet/breadmapbackend/domain/flag/FlagBakeryRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/flag/FlagController.java
src/main/java/com/depromeet/breadmapbackend/domain/flag/FlagRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/flag/FlagService.java
src/main/java/com/depromeet/breadmapbackend/domain/flag/FlagServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/review/ReviewRepository.java
src/test/java/com/depromeet/breadmapbackend/domain/flag/FlagServiceImplTest.java
src/test/resources/flag-test-data.sql

Refactor : FlagService

---

src/main/java/com/depromeet/breadmapbackend/global/security/token/RedisTokenUtils.java

-  NullPointException 발생할 수 있는 코드 변경 & 공통 사용 로직 메소드 추출

fix : 2023-07-06 18:01:53 오류 수정

---

src/main/java/com/depromeet/breadmapbackend/domain/bakery/Bakery.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryServiceImpl.java

- 기존 getOrDefault 메소드의 default 값으로 null을 넘겨 이후 메소드에서 NPE 발생 -> empty list를 default 값으로 수정
<br/>

fix : 2023-07-07 18:04:11 발생 오류 수정

---

src/main/java/com/depromeet/breadmapbackend/domain/bakery/BakeryServiceImpl.java

getBakeryList 요청시 응답 데이터 없을때 empty list 처리

fix : getBakeryList 요청시 응답 데이터 없을때 empty list 처리

---

src/docs/asciidoc/index.adoc

feat. index.html

---

src/main/java/com/depromeet/breadmapbackend/domain/admin/feed/controller/FeedAdminController.java
src/main/java/com/depromeet/breadmapbackend/domain/admin/feed/dto/request/FeedSearchRequest.java
src/main/java/com/depromeet/breadmapbackend/domain/admin/feed/dto/response/FeedContentInfo.java
src/main/java/com/depromeet/breadmapbackend/domain/admin/feed/repository/FeedQueryRepositoryImpl.java
src/main/resources/static/docs/admin.html
src/main/resources/static/docs/auth.html
src/main/resources/static/docs/bakery.html
src/main/resources/static/docs/feed.html
src/main/resources/static/docs/flag.html
src/main/resources/static/docs/image.html
src/main/resources/static/docs/notice.html
src/main/resources/static/docs/post.html
src/main/resources/static/docs/review.html
src/main/resources/static/docs/search.html
src/main/resources/static/docs/user.html
src/test/java/com/depromeet/breadmapbackend/domain/admin/feed/controller/FeedAdminControllerTest.java
src/test/java/com/depromeet/breadmapbackend/domain/admin/feed/repository/FeedRepositoryTest_Search.java

feat. createdAt, categoryName 추가

---

src/main/resources/application-stage.yml

flyway 이력관리 테이블이 없을 경우 최초 버전 0변경

fix. flyway 이력관리 테이블이 없을 경우 최초 버전 0변경

---

src/main/java/com/depromeet/breadmapbackend/global/security/filter/JwtAuthenticationFilter.java

fix : jwtfilter 수정

---

src/main/java/com/depromeet/breadmapbackend/global/infra/AmazonSQSConfig.java

hotfix: SQSConfig final 제거

---

src/main/java/com/depromeet/breadmapbackend/domain/admin/feed/controller/CurationPushNotificationScheduler.java
src/main/resources/static/docs/admin.html
src/main/resources/static/docs/auth.html
src/main/resources/static/docs/bakery.html
src/main/resources/static/docs/feed.html
src/main/resources/static/docs/flag.html
src/main/resources/static/docs/image.html
src/main/resources/static/docs/index.html
src/main/resources/static/docs/notice.html
src/main/resources/static/docs/post.html
src/main/resources/static/docs/review.html
src/main/resources/static/docs/search.html
src/main/resources/static/docs/user.html

docs : api문서 생성 & 큐레이션 알림 시간 변경

---

src/main/java/com/depromeet/breadmapbackend/domain/post/PostServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/post/PostTopic.java
src/main/resources/static/docs/admin.html
src/main/resources/static/docs/auth.html
src/main/resources/static/docs/bakery.html
src/main/resources/static/docs/feed.html
src/main/resources/static/docs/flag.html
src/main/resources/static/docs/image.html
src/main/resources/static/docs/index.html
src/main/resources/static/docs/notice.html
src/main/resources/static/docs/post.html
src/main/resources/static/docs/review.html
src/main/resources/static/docs/search.html
src/main/resources/static/docs/user.html
src/test/java/com/depromeet/breadmapbackend/domain/post/PostControllerTestSteps.java

Feat : 커뮤니티 먹은 빵 자랑 카테고리 추가.

---

src/main/java/com/depromeet/breadmapbackend/domain/post/PostQueryRepository.java

hotfix : 커뮤니티 관리자 숨긴글 출력 오류 수정

---

src/main/java/com/depromeet/breadmapbackend/domain/report/ReportType.java

- 먹은빵자랑 관련 오류 수정 (카테고리 enum 추가)

hotfix : 먹은빵자랑 관련 오류 수정

---

src/main/java/com/depromeet/breadmapbackend/domain/notice/NoticeServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/global/infra/SecurityConfig.java

- eventPublisher async 제거 & securityConfig 수정

hotfix : eventPublisher async 제거 & securityConfig 수정

---

src/main/java/com/depromeet/breadmapbackend/domain/notice/FcmService.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/NoticeFactoryProcessorImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/BakeryAddNoticeFactory.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/CurationNoticeFactory.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/NewEventNoticeFactoryImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/ReportBakeryAddNoticeFactory.java
src/main/java/com/depromeet/breadmapbackend/domain/post/comment/CommentServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/review/comment/ReviewCommentServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/review/like/ReviewLikeServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/global/infra/properties/CustomAWSS3Properties.java
src/main/resources/application-prod.yml
src/main/resources/application-stage.yml
src/test/java/com/depromeet/breadmapbackend/domain/admin/bakery/service/AdminBakeryServiceTest.java
src/test/resources/application.yml

Feat : 알림 이미지 추가 & 안드로이드 채널 설정

---

src/main/resources/static/docs/admin.html
src/main/resources/static/docs/auth.html
src/main/resources/static/docs/bakery.html
src/main/resources/static/docs/feed.html
src/main/resources/static/docs/flag.html
src/main/resources/static/docs/image.html
src/main/resources/static/docs/notice.html
src/main/resources/static/docs/post.html
src/main/resources/static/docs/review.html
src/main/resources/static/docs/search.html
src/main/resources/static/docs/user.html

docs : api 문서 최신화

---

src/main/java/com/depromeet/breadmapbackend/domain/notice/NoticeServiceImpl.java

hotfix : 알림 중복전송 오류

---

src/main/java/com/depromeet/breadmapbackend/domain/admin/feed/controller/CurationPushNotificationScheduler.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/NoticeServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/BakeryAddNoticeFactory.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/CurationNoticeFactory.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/NewEventNoticeFactoryImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/token/NoticeTokenRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/user/UserRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/user/UserServiceImpl.java

hotfix : 알림내역 중복 생성 오류 수정

---

src/main/java/com/depromeet/breadmapbackend/global/security/token/JwtTokenProvider.java

hotfix : jwtTokenProvider rollback

hotfix : jwtTokenProvider rollback

---

src/main/java/com/depromeet/breadmapbackend/domain/post/PostQueryRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/post/PostServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/post/comment/Comment.java
src/main/java/com/depromeet/breadmapbackend/domain/post/comment/CommentJpaRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/post/comment/CommentRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/post/comment/CommentRepositoryImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/post/comment/CommentServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/post/comment/dto/Command.java
src/test/java/com/depromeet/breadmapbackend/domain/post/PostServiceImplTest.java
src/test/java/com/depromeet/breadmapbackend/domain/post/comment/CommentServiceTest.java

hotfix : comment 알림 오류 수정

---

src/main/java/com/depromeet/breadmapbackend/domain/search/OpenSearchLoadTestScheduler.java

- 구체적이고 기술적인 변경 내용 1
<br/>
- 리뷰어가 참고할 수 있는 내용 1
<br/>
closed #{이슈번호}
---
> PR 생성 시 지워주세요
> 제목 tag는 아래의 prefix를 따라주세요
```
feat: 기능 구현
refactor: 리팩토링
fix: 오류 해결
hotfix: 긴급 내용
docs: 문서 관련
chore: 사소하거나 애매한 것들
test: 테스트 관련
build: 빌드 관련 설정
revert: 롤백
style: 코드 스타일 수정
infra: 인프라 관련
```

feat: OpenSearch test scheduler profile 수정

---

src/main/java/com/depromeet/breadmapbackend/domain/notice/FcmService.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/Notice.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/NoticeServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/dto/NoticeDto.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/dto/NoticeEventDto.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/dto/NoticeFcmDto.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/NoticeType.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/CommentLikeNoticeFactory.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/CommunityCommentNoticeFactory.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/FollowNoticeFactory.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/RecommentFactory.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/ReviewCommentNoticeFactory.java
src/main/java/com/depromeet/breadmapbackend/domain/post/comment/CommentJpaRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/post/comment/CommentRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/post/comment/CommentRepositoryImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/post/comment/CommentServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/review/ReviewQueryRepository.java
src/test/java/com/depromeet/breadmapbackend/domain/notice/NoticeControllerTest.java
src/test/java/com/depromeet/breadmapbackend/domain/notice/NoticeServiceImplTest.java
src/test/resources/notice-test-data.sql

hotfix : 푸쉬알림 오류사항 수정

---

src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/BakeryAddNoticeFactory.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/CommentLikeNoticeFactory.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/ReportBakeryAddNoticeFactory.java
src/main/java/com/depromeet/breadmapbackend/domain/post/comment/CommentServiceImpl.java
src/main/resources/static/docs/admin.html
src/main/resources/static/docs/auth.html
src/main/resources/static/docs/bakery.html
src/main/resources/static/docs/feed.html
src/main/resources/static/docs/flag.html
src/main/resources/static/docs/image.html
src/main/resources/static/docs/index.html
src/main/resources/static/docs/notice.html
src/main/resources/static/docs/post.html
src/main/resources/static/docs/review.html
src/main/resources/static/docs/search.html
src/main/resources/static/docs/user.html

Hotfix : 푸쉬 알림 오류 수정 사항 반영

---

src/main/java/com/depromeet/breadmapbackend/domain/post/comment/CommentServiceImpl.java

hotfix : 대댓글 알림  수정

---

src/main/java/com/depromeet/breadmapbackend/domain/notice/NoticeQueryRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/post/comment/CommentServiceImpl.java

hotfix : 알림 정렬순서 & 오류 수정

---

src/main/java/com/depromeet/breadmapbackend/domain/admin/post/domain/service/impl/PostAdminServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/FcmService.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/Notice.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/NoticeServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/dto/NoticeDto.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/dto/NoticeFcmDto.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/CommentLikeNoticeFactory.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/CommunityCommentNoticeFactory.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/CommunityLikeNoticeFactory.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/FollowNoticeFactory.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/RecommentFactory.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/ReviewCommentNoticeFactory.java
src/main/java/com/depromeet/breadmapbackend/domain/notice/factory/push/ReviewLikeNoticeFactory.java
src/main/resources/static/docs/admin.html
src/main/resources/static/docs/auth.html
src/main/resources/static/docs/bakery.html
src/main/resources/static/docs/feed.html
src/main/resources/static/docs/flag.html
src/main/resources/static/docs/image.html
src/main/resources/static/docs/notice.html
src/main/resources/static/docs/post.html
src/main/resources/static/docs/review.html
src/main/resources/static/docs/search.html
src/main/resources/static/docs/user.html
src/test/java/com/depromeet/breadmapbackend/domain/notice/NoticeControllerTest.java

hotfix : api 문서 반영 & fcm data 추가

---

src/main/java/com/depromeet/breadmapbackend/domain/notice/FcmService.java

hotfix : firebase exception 수정

---

src/main/java/com/depromeet/breadmapbackend/domain/admin/feed/controller/CurationPushNotificationScheduler.java
src/main/java/com/depromeet/breadmapbackend/domain/auth/AuthServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/user/User.java
src/test/java/com/depromeet/breadmapbackend/domain/notice/NoticeControllerTest.java

hotfix : 큐레이션 cron 시간 수정

---

src/main/java/com/depromeet/breadmapbackend/domain/admin/carousel/domain/service/CarouselManagerService.java
src/main/java/com/depromeet/breadmapbackend/domain/admin/carousel/domain/service/CarouselManagerServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/admin/feed/service/CurationFeedService.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/ranking/ScoredBakeryJpaRepository.java
src/test/java/com/depromeet/breadmapbackend/domain/admin/feed/controller/FeedAdminControllerTest.java
src/test/java/com/depromeet/breadmapbackend/utils/ControllerTest.java

feat : 케러셀 큐레이션 & 이벤트 통합 출력 수정

---

src/main/java/com/depromeet/breadmapbackend/domain/community/domain/Community.java
src/main/java/com/depromeet/breadmapbackend/domain/community/domain/CommunityImage.java
src/main/java/com/depromeet/breadmapbackend/domain/community/domain/CommunityReview.java
src/main/java/com/depromeet/breadmapbackend/domain/community/domain/CommunityType.java
src/main/java/com/depromeet/breadmapbackend/domain/community/domain/TempBakerySource.java
src/main/java/com/depromeet/breadmapbackend/domain/community/domain/TempProductSource.java

feat: community 도메인 정의

---

src/main/java/com/depromeet/breadmapbackend/domain/challenge/ApprovalType.java
src/main/java/com/depromeet/breadmapbackend/domain/challenge/VerificationHistory.java

feat: commit new package initialization

---

.github/workflows/prod_CD.yml

- 새 prod 계정의 ECR로 업로드 되도록 임시 변경

refactor: tmp update prod_CD.yml

---

src/main/java/com/depromeet/breadmapbackend/domain/bakery/tag/Tag.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/tag/TagCategory.java
src/main/java/com/depromeet/breadmapbackend/domain/bakery/tag/TagRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/challenge/Challenge.java
src/main/java/com/depromeet/breadmapbackend/domain/challenge/ChallengeController.java
src/main/java/com/depromeet/breadmapbackend/domain/challenge/ChallengeQuery.java
src/main/java/com/depromeet/breadmapbackend/domain/challenge/ChallengeRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/challenge/ChallengeService.java
src/main/java/com/depromeet/breadmapbackend/domain/challenge/ChallengeServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/challenge/breaddiary/BreadDiary.java
src/main/java/com/depromeet/breadmapbackend/domain/challenge/breaddiary/BreadDiaryController.java
src/main/java/com/depromeet/breadmapbackend/domain/challenge/breaddiary/BreadDiaryRepository.java
src/main/java/com/depromeet/breadmapbackend/domain/challenge/breaddiary/BreadDiaryService.java
src/main/java/com/depromeet/breadmapbackend/domain/challenge/breaddiary/BreadDiaryServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/challenge/breaddiary/dto/AddBreadDiaryDto.java
src/main/java/com/depromeet/breadmapbackend/domain/challenge/breaddiary/dto/AddBreadDiaryRequest.java
src/main/java/com/depromeet/breadmapbackend/domain/search/OpenSearchServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/domain/search/SearchServiceImpl.java
src/main/java/com/depromeet/breadmapbackend/global/exception/DaedongStatus.java

- 
챌린지 참가 가능 여부 조회 및 참가 신청이 동시에 진행된다.
- 참가가 불가능한 경우 에러 코드 및 에러 메세지로 내용 정의해서 리턴한다.
<br/>
closes #DDB-247
---

feat: 챌린지 참가 API #DDB-247
